version: '3'
services:
  app1:
    build: ./app1
    volumes:
      - ./storage:/storage:ro

  app2:
    build: ./app2
    volumes:
      - ./storage:/storage:ro

  nginx:
    build: ./nginx
    ports:
    - "445:445"
    depends_on:
      - app1
      - app2
